version: "4.37.1"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mariadb:10.4
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: sdlc_programmer
    ports:
      - "3309:3308"
    volumes:
    - ./sdlc_programmer_data:/var/lib/mysql
